name: Publish App
run-name: ${{ github.actor }} is publishing ${{ github.repository }} 🚀

on:
  push:
    branches:
      - main

jobs: 
  Publish-Unstable:
    runs-on : ubuntu-latest
    steps:
      - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_SHA}
      shell: bash
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_REGISTRY_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/bejibe/myapp:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/bejibe/myapp:latest

on:
  push:
    tags:        
      - v*

jobs: 
  Publish-Stable:
    runs-on : ubuntu-latest
    steps:
      - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      shell: bash
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_REGISTRY_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/bejibe/myapp:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/bejibe/myapp:latest
