name: Publish App
run-name: ${{ github.actor }} is publishing ${{ github.repository }} 🚀

on:
  push:
    branches:
      - master

jobs: 
  Publish-Unstable:
    runs-on : ubuntu-latest
    steps:
      - name: Set Version
        id: get_version
        run: echo ${GITHUB_SHA} >> VERSION
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_REGISTRY_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src/ActApp/webapp/Dockerfile
          push: true
          tags: |
            ghcr.io/bejibe/myapp:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/bejibe/myapp:latest
