name: Publish App
run-name: ${{ github.actor }} is publishing ${{ github.repository }} 🚀

on:
  push:
    branches:
      - master

jobs: 
  Publish-Unstable:
    runs-on : ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Version
        run: echo ::set-output name=VERSION::${GITHUB_SHA}
        id: get_version
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./src/ActApp/webapp/
          push: true
          tags: |
            ghcr.io/bejibe/myapp:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/bejibe/myapp:latest
